### ISSUE TITLE
Add documentation to create multiple certificates

### ISSUE THREAD

**Issue by enricostano** [coopdevs/certbot_nginx#11]
With https://github.com/coopdevs/certbot_nginx/pull/10 we moved the creation of the certificate to its own task `certificate.yml`. We did this in order to be able to create multiple certificates calling that task multiple times.

We need to add some documentation covering this use case.

Briefly the steps are:

1. Use the role as usual without passing the `domain_name` variable (this will not create any certificate)
2. `include_role` in a separate local role and call the `certificate.yml` multiple times (e.g. https://github.com/coopdevs/coopdevs-provisioning/pull/11)

**Comment by danypr92** [comment]
This issue was fixed with the #12, no?

Can we close it?

**Comment by enricostano** [comment]
Yep, please use GitHub syntax in PR descriptions to get it done automatically:

https://help.github.com/en/articles/closing-issues-using-keywords
