### ISSUE TITLE
Broken build due to linter issue

### ISSUE THREAD

**Issue by enricostano** [coopdevs/certbot_nginx#17]
Since we merged #15 and #16 we have to "clean up" the repo:
https://travis-ci.org/coopdevs/certbot_nginx/jobs/510276548#L676

EDIT: basically line https://github.com/coopdevs/certbot_nginx/blob/master/tasks/certificate.yml#L8 is too long.

**Comment by danypr92** [comment]
I fix the Travis execution in the #20. Only add the `noqa` to the command line too long with the error code to skip.

Can we say that that PR fix this issue? :angel:

**Comment by enricostano** [comment]
> Can we say that that PR fix this issue?

@danypr92 yep, but give a look at the Pr's comments about implementation.
