### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by Matt-Yorkley** [coopdevs/certbot_nginx#22]
Python3 is the standard now for Ansible. 

Installation of the package: `python-certbot-nginx` is hard-coded in:

https://github.com/coopdevs/certbot_nginx/blob/2e388c4c46410f40691726cad7e0cf181348a237/tasks/main.yml#L12-L15

 For the plugin to work with Python3, the required package is: `python3-certbot-nginx`

**Comment by Matt-Yorkley** [comment]
On further testing, it looks like it fails anyway when using the python3 interpreter. :see_no_evil:

**Comment by raneq** [comment]
Could you post the errors? Do you think there may be commands in this playbook incompatible with python3? I sincerely don't know how wide it is :/
@danypr92 has done work with this before, maybe he can have a look at it.

**Comment by oyale** [comment]
Closing because it must be already fixed, given that we're using it with python3.8 as default interpreter.
