### ISSUE TITLE
Instalation problem

### ISSUE THREAD

**Issue by tenaz3** [coopdevs/certbot_nginx#28]
`ansible-galaxy install coopdevs.certbot_nginx`
```
[WARNING]: - coopdevs.certbot_nginx was NOT installed successfully: Unable to compare role versions (0.0.4, v0.2.0, 0.0.2, 0.0.3, v0.1.0, 0.0.1) to determine the most recent version due to incompatible
version formats. Please contact the role author to resolve versioning conflicts, or specify an explicit role version to install.
```

**Comment by raneq** [comment]
So bad!

From all versions (0.0.4, v0.2.0, 0.0.2, 0.0.3, v0.1.0, 0.0.1), the most recent version is v0.2.0.
It's up to coopdevs, but if you want the most recent starting today's latest version, you can try to set your required one to `>=v0.2.0`.

Let's see if @coopdevs/contributors have a wider fix.

Cheers!

**Comment by sauloperez** [comment]
Apologies. We need to better document this so keep consistent version numbers.
