### ISSUE TITLE
Update metadata

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/certbot_nginx#8]
We need to update 

https://github.com/coopdevs/certbot_nginx/blob/2f24488da33d11b4761d99b63cb9b6324da721eb/meta/main.yml#L10-L13

To add Ubuntu Trusty. It is supposed to work in there too.

**Comment by danypr92** [comment]
In which projects are we using Ubuntu Trusty?

**Comment by sauloperez** [comment]
AFAIK some instances in OFN might do

**Comment by danypr92** [comment]
Is because I need to test the new PR #9 with Trusty also. :sweat_smile:

**Comment by danypr92** [comment]
I update the #9 to allow also Ubuntu Trusty.
